### ISSUE TITLE
Can't derive Diff for a case class with all default arguments

### ISSUE THREAD

**Issue by laughedelic** [softwaremill/diffx#104]
Example:

```scala
import com.softwaremill.diffx.Diff

// both args have defaults:
case class Buh(
  a: String = "",
  b: Int = 1
)

// fails
Diff[Buh]
```

Here is a runnable snippet:
https://scastie.scala-lang.org/kKEQ1SZzTmudSGJGvO5BGg

This broke with the Magnolia version upgrade: https://github.com/softwaremill/diffx/pull/93

I tried overriding Magnolia version to the latest, but it didn't help. Using latest Diffx with overriden Magnolia 0.12.8 _does_ work. 

So I know it's a problem with Magnolia, but I thought it's worth reporting here first. Let me know if I should report it there instead.

**Comment by laughedelic** [comment]
Actually I think it's this one: https://github.com/propensive/magnolia/issues/227

Feel free to close this issue.

**Comment by ghostbuster91** [comment]
Hi,

Thanks for reporting. I just release new version 0.3.26 with updated magnolia, so it should be available in maven central within a couple of hours.

**Comment by laughedelic** [comment]
Thanks for the fast reaction!

**Comment by laughedelic** [comment]
@ghostbuster91 I think the version with the fix is 0.14.3: https://github.com/propensive/magnolia/compare/v0.14.2...v0.14.3
And Diffx 0.3.26 is updated to 0.14.2. Could you release another upgrade?

**Comment by ghostbuster91** [comment]
@laughedelic Lol,I didn't expect that :) Sure, new release is rolling....

**Comment by laughedelic** [comment]
Thanks again!
