### ISSUE TITLE
0.2.2 does not appear to be published to Maven Central

### ISSUE THREAD

**Issue by dbuschman7** [softwaremill/diffx#18]
The latest version that Maven Central is reporting is 0.2.0

**Comment by ghostbuster91** [comment]
Yes, it looks like something has changed between sbt 1.2.8 and 1.3.1 in terms of publishing artifacts to maven central. I was able to continue process manually, so the 0.2.2 release should be available in a couple of minutes. Sorry for the inconvenience.

**Comment by francisdb** [comment]
It's available

**Comment by dbuschman7** [comment]
Thank you very much! :)
