### ISSUE TITLE
NullPointerException is thrown when you compare 2 instances of a case class and one of the instances has a null value and the other one has a valid string.

### ISSUE THREAD

**Issue by emilianotebes** [softwaremill/diffx#195]
Affected Version: 0.4.0

Steps to reproduce:
 1. create a case class with a string field
 2. create an instance of that class with that field null
 3. create another instance of that class with a valid value
 4. compare

 For further details check [sample project](https://github.com/emilianotebes/diffx-npe/blob/main/src/test/scala/ExampleSpec.scala)

**Comment by ghostbuster91** [comment]
Hi, thanks for very detailed report and sorry for the delay. Let me look at it...

**Comment by ghostbuster91** [comment]
Fixed in 0.4.1 🎉

**Comment by emilianotebes** [comment]
Thanks for the answer and the fix!
