### ISSUE TITLE
Scala 2.11 cross compile

### ISSUE THREAD

**Issue by f1yegor** [softwaremill/diffx#20]
I would like to use this library with scala 2.11. 
From quick look there is upstream dependency on `neme-plugin`.
Is it difficult to support 2.11?

**Comment by ghostbuster91** [comment]
I am not sure how about the `neme-plugin` but the biggest problem is the lack of support for 2.11 in magnolia. See https://github.com/propensive/magnolia/issues/171 . Once it will be fixed I can try to make a release for 2.11

**Comment by f1yegor** [comment]
yes, I have seen this and tried to compile with "0.10.0" version of magnolia and without neme-plugin. but got problems and created this issue to see bigger picture).

**Comment by ghostbuster91** [comment]
Ok, so I tried it myself and after fixing obvious stuff I hit a wall. 
For some reason diffx couldn't derive a type class for `Foo` where `Foo` is defined as:
```
sealed trait Parent
case class Bar(s: String, i: Int) extends Parent
case class Foo(bar: Bar, b: List[Int], parent: Option[Parent]) extends Parent
```
I suspect that this is a bug in magnolia v0.10.0. I wanted to see if I can reproduce the same behavior directly in magnolia itself, but after switching to v0.10.0 tag I don't know even how to run tests. I tried `tests/test` as always but it does nothing.

**Comment by leobenkel** [comment]
Would love that as well ! Thank you

**Comment by ghostbuster91** [comment]
A lot of issues have been resolved in magnolia since it dropped support for scala 2.11. Sorry but I don't think that releasing diffx for scala 2.11 with magnolia 0.10.0 is worth it. Once magnolia restores it I will be happy to do it as well.

**Comment by f1yegor** [comment]
thank you for response. I'll close an issue
