### ISSUE TITLE
matchTo does not work with value classes

### ISSUE THREAD

**Issue by francisdb** [softwaremill/diffx#21]
```scala

case class Foo(private val id: String) extends AnyVal

Foo("test") should equal(Foo("test"))
Foo("test") should matchTo(Foo("test"))
```

> could not find implicit value for evidence parameter of type com.softwaremill.diffx.Diff[io.waylay.engine.runtime.format.Foo]
  [error]     Foo("test") should matchTo(Foo("test"))

**Comment by ghostbuster91** [comment]
In order to derive automatically type classes for products magnolia needs to access their fields. In your example `id` is marked as `private` so magnolia has no way to do that. Either remove `private` modifier or create an explicit instance of `Diff[Foo]`.

**Comment by francisdb** [comment]
ok, closing issue

**Comment by adamw** [comment]
maybe this should go to a FAQ in the README or sth like that? :)
