### ISSUE TITLE
POM contains non-existent scm.url

### ISSUE THREAD

**Issue by fthomas** [softwaremill/diffx#43]
The [POM](https://search.maven.org/artifact/com.softwaremill.diffx/diffx-core_2.12/0.3.9/jar) of the latest version contains non-existent URLs:
```xml
    <scm>
        <url>https://github.com/softwaremill/diffx-core</url>
        <connection>git@github.com:softwaremill/diffx-core.git</connection>
    </scm>
```

**Comment by adamw** [comment]
Seems that sbt somehow generates these basing on the sbt-subproject name. But I have no idea where ;) Our release includes: https://github.com/softwaremill/sbt-softwaremill/blob/master/src/main/scala/com/softwaremill/Publish.scala#L90-L92, which would suggest that no scm information should be included in the pom. But somehow it is - no idea where. If you would know which sbt setting it is, pointers welcome! :)

**Comment by fthomas** [comment]
I guess it is using `scmInfo`:
```
sbt:diffx> core/scmInfo
[info] Some(ScmInfo(https://github.com/softwaremill/diffx-core, git@github.com:softwaremill/diffx-core.git, None))
sbt:diffx> inspect core/scmInfo
[info] Setting: scala.Option[sbt.librarymanagement.ScmInfo] = Some(ScmInfo(https://github.com/softwaremill/diffx-core, git@github.com:softwaremill/diffx-core.git, None))
[info] Description:
[info]  Basic SCM information for the project.
[info] Provided by:
[info]  ProjectRef(uri("file:/home/frank/data/code/diffx/"), "core") / scmInfo
[info] Defined at:
[info]  (xerial.sbt.Sonatype.sonatypeSettings) Sonatype.scala:79
[info] Dependencies:
[info]  core / sonatypeProjectHosting
[info] Reverse dependencies:
[info]  core / projectInfo
[info] Delegates:
[info]  core / scmInfo
[info]  ThisBuild / scmInfo
[info]  Global / scmInfo
[info] Related:
[info]  Global / scmInfo
[info]  scalatest / scmInfo
[info]  tagging / scmInfo
[info]  specs2 / scmInfo
[info]  scmInfo
sbt:diffx>
```
You could tweak `scmInfo` and then verify with `makePom` if it has any effect on the generated POMs.

**Comment by ghostbuster91** [comment]
Great thanks for reporting and for the tip. Next release will contain the fix.

**Comment by adamw** [comment]
Maybe we can fix it in sbt-softwaremill?
