### ISSUE TITLE
add support for utest

### ISSUE THREAD

**Issue by ghostbuster91** [softwaremill/diffx#5]
https://github.com/lihaoyi/utest

**Comment by Slakah** [comment]
I would be interested in tackling this if noone has any objections?

**Comment by ghostbuster91** [comment]
Sure, pr's are more than welcome :)

**Comment by ghostbuster91** [comment]
@Slakah Hi, how is it going? Do you need any help?

**Comment by Slakah** [comment]
> Hi, how is it going? Do you need any help?

Ah, sorry. Completely forgot about this, not really looking at this atm. Tempted to say that https://github.com/scalameta/munit would be a better utest alternative, which has the coloured diff functionality built in.

**Comment by ghostbuster91** [comment]
Sure, you might be right ;)
