### ISSUE TITLE
I added ZIO Test module.

### ISSUE THREAD

**Issue by pme123** [softwaremill/diffx#62]
Hi there
I created a Module to add support for ZIO test.

Here is the commit: https://github.com/pme123/diffx/commit/b1211cc89ce3f011dc2e5f40c1625a8a1f5db581

Is it ok if I create a Pull Request?

**Comment by ghostbuster91** [comment]
Hi, 

First of all you don't have to ask anyone for permission to create a PR ;) It is also easier to review and discuss if you do.

So yes, please create the PR and we will discuss your code there to keep the discussion in one place.

**Comment by pme123** [comment]
ok, I did;) It was not so clear to me  when I read the Contributing.md. So I wanted to be sure;).
