### ISSUE TITLE
Writing generic methods that use matchTo

### ISSUE THREAD

**Issue by gregghz** [softwaremill/diffx#68]
I'm having trouble writing a method that uses matchTo on a generic type. I'm using the scala test integration, but using Diff.apply directly produces the same results. For example:

```
def testSomething[A](expected: A, actual: A): Unit = {
  expected should matchTo(actual)
}
```

This produces the following error:

```
[error] ... could not find implicit value for evidence parameter of type com.softwaremill.diffx.Diff[A]
[error]     expected should matchTo(actual)
[error]                            ^
```

Changing the definition to this:

```
def testSomething[A: Diff](expected: A, actual: A): Unit = {
  expected should matchTo(actual)
}
```

Moves the error to the callsite. I'm using simple case classes when calling this method. How can I acquire an implicit instance of Diff for my case class?

**Comment by ghostbuster91** [comment]
Hi, 

Sorry for long delay. I am not sure if I understand you correctly. There is already such a function - `compare` defined in diffx package object. Here : https://github.com/softwaremill/diffx/blob/master/core/src/main/scala-common/com.softwaremill.diffx/DiffxSupport.scala#L10

Your second function also looks good to me. If you are using a simple case class then everything should be derived automatically. Can you provide more details?

**Comment by gregghz** [comment]
Thanks for the reply, I tried to create a minimal example and things worked fine. It must be something weird in my project. I'll close for now.
